### ISSUE TITLE
可以增加查询时自动发音的功能吗？

### ISSUE THREAD

**Issue by pavison** [maicss/chrome-shanbay-v2#14]
我在设置中所设置的“默认发音”只是选择是英语还是美语发音，实际上并不能在我查询单词的时候自动发音，是我设置的有问题吗？

**Comment by maicss** [comment]
默认就是不自动发音的，晚上我看看怎么回事。

**Comment by maicss** [comment]
修改好了，但是Chrome要求必须给个隐私使用政策的连接才给发布新的包，意味着我必须弄个网站写点隐私政策才可以，再等等吧……

**Comment by maicss** [comment]
审核通过了，再试试看。

**Comment by pavison** [comment]
wow 感谢作者！神速！
