### ISSUE TITLE
通知能否提供开关功能？

### ISSUE THREAD

**Issue by networm** [maicss/chrome-shanbay-v2#4]
并不需要通知功能，由于没有设置界面，无法关闭。

**Comment by maicss** [comment]
好的

**Comment by networm** [comment]
感谢！

maicss <notifications@github.com> 于2018年10月8日周一 下午11:02写道：

**Comment by maicss** [comment]
这个选项是有的，是扇贝的API变了，导致选项界面出不来，我明天处理一下

**Comment by maicss** [comment]
扇贝认证的API关闭了，虽然插件是可以做爬虫直接发送请求，也能实现功能，但是我最近工作上的事情比较多，而且这样做更加复杂。我最近没有修改这个的打算。

而且扇贝这个API个自己网站使用的数据库不是一个，单词库不一样，释义也不一样，当初是因为我比较喜欢在网页上添加生词，在手机扇贝客户端能直接看到添加的生词。（但是后来也没按时背单词🤪）

建议先使用[saladict](https://github.com/crimx/ext-saladict/wiki)吧。

**Comment by networm** [comment]
那能不能直接把通知这个功能关了，不需要选项界面，我认为大部分人并不需要修改选项，而且也不需要通知。

**Comment by networm** [comment]
saladict 只能查本地的词库，而我需要的是添加到扇贝单词中，第二天直接背的。

**Comment by maicss** [comment]
好吧，为了你这个唯一的用户，我用其他办法，让这个插件正常工作🤪

**Comment by networm** [comment]
好的，非常感谢，那我向同事朋友多推荐使用这个吧！

**Comment by networm** [comment]
非常感谢，Chrome 已自动更新扩展，不再有通知了！

**Comment by networm** [comment]
如果已经修好了，是不是考虑把插件停止使用公告撤了？

**Comment by maicss** [comment]
嗯，我趁热打铁又重构了一次🙃

**Comment by networm** [comment]
我建议尝试将自己想要看的英文书变成扇贝单词书，这样背起来较有针对性。
如果要制作扇贝单词书，可以参考：[塞尔达传说：荒野之息 扇贝单词书 - 狂飙](https://networm.me/2018/02/04/zelda-shanbay-wordbook/)

**Comment by maicss** [comment]
这个不错哦。不过我get到点，你是向我推荐你弄的东西还是想让我考虑一下添加这个功能？

**Comment by networm** [comment]
并不是推荐东西也不是添加功能，就是给一个学习英语的思路，结合自己实际要用的来学习。

而且这个东西也没什么难度，可能你自己用 js 写这个功能更快更方便。

maicss <notifications@github.com>于2018年10月15日 周一10:40写道：

**Comment by maicss** [comment]
自从我写好这个之后，我就再也没背过英语单词😂

**Comment by networm** [comment]
好像通知还会弹，macOS 10.13.6 Chrome 69

狂飙 <zzjbcn@gmail.com>于2018年10月15日 周一11:19写道：

**Comment by maicss** [comment]
设置页面有个开关的

**Comment by networm** [comment]
已经关闭了，还是弹了

maicss <notifications@github.com>于2018年10月15日 周一14:30写道：

**Comment by maicss** [comment]
呃，等我下班回去看看吧

**Comment by maicss** [comment]
好了，等会应该会自动更新。

**Comment by networm** [comment]
已经更新上了，等3小时看看


maicss <notifications@github.com>于2018年10月15日 周一21:39写道：

**Comment by maicss** [comment]
@networm 老哥，上次更新之后，一直报错，非常抱歉。你这是不用了么 😂

**Comment by networm** [comment]
没有啊，一直在用，3 台电脑上都没有问题，而且没注意到有报错啊。

**Comment by maicss** [comment]
哦，对。你登录了，我在公司电脑上没登。反正前几天又发布了一个版本，修好了。我在想这个bug会不会让你很烦 😂

**Comment by networm** [comment]
不会的，我必须要登录的，因为遇到不会的单词马上就加到生词本里了。
