### ISSUE TITLE
Future support for 柯林斯词典?

### ISSUE THREAD

**Issue by hayschan** [maicss/chrome-shanbay-v2#5]
Will there be support for 柯林斯词典?

Like this [chrome extension](https://chrome.google.com/webstore/detail/%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91%E6%9F%AF%E6%9E%97%E6%96%AF%E8%AF%8D%E5%85%B8%2B%E6%89%87%E8%B4%9D%E7%94%9F%E8%AF%8D%E6%9C%AC/mkohdjbfagmlcaclajmadgkojelkbbfj) does: 
![image](https://user-images.githubusercontent.com/25737801/50197686-31a4e500-0383-11e9-80e9-59fcb899bf21.png)

> 相比于两三个中文字的单词意思解释，柯林斯词典提供了一定的英文语境可以帮我们更准确地理解一个单词的意思，并加深记忆。

P.S. Greetings to you, my friend.  The extension has helped me a lot - makes life easy.  👍

**Comment by maicss** [comment]
这个插件的原意是利用扇贝的客户端，比如iOS，同步单词本，然后利用其他时间，背今天添加的单词之类的，用其他词库的话，就可能出现，扇贝的单词库没有这个词之类的。

你这给的这个链接不是搞定这个事情了吗，为啥还要我添加这个功能捏？
