### ISSUE TITLE
弹出后无法收回

### ISSUE THREAD

**Issue by Mtax** [maicss/chrome-shanbay-v2#6]
![image](https://user-images.githubusercontent.com/5325221/99939461-0ca62180-2da5-11eb-8b1b-26a786b6b140.png)

**Comment by Mtax** [comment]
加个关闭功能是不是更好

**Comment by maicss** [comment]
默认是点击页面就消失的。而且我这边测试的是正常的，你能看看`ctrl+shift+i`的``console`面板有什么红色的报错吗？

**Comment by maicss** [comment]
点击网页关闭弹窗的体验不是更好么。暂时不考虑加关闭按钮。

**Comment by Mtax** [comment]
@maicss 如果默认行为正常，没必要加按钮；
