### ISSUE TITLE
无法点击空白处关闭弹窗

### ISSUE THREAD

**Issue by networm** [maicss/chrome-shanbay-v2#8]
## 问题

双击单词后可以正常释义弹窗，但是再点击空白处发现无法关闭。

## 环境

扇贝助手v2 2.0.2
Chrome 109.0.5414.119
Windows 10 21H2
macOS 11.7.1

## 报错

```
Uncaught TypeError: Cannot read properties of undefined (reading 'some')
    at HTMLDocument.<anonymous> (main.js:261:19)
(anonymous) @ main.js:261
```

**Comment by maicss** [comment]
注意到了，正在修复，顺便升级到第三版的扩展规范。不过这段时间比较忙，可能进度比较慢。

**Comment by networm** [comment]
好的。因为平时遇到不会的单词就加到生词本里每天背，所以这个扩展是比较常用且重要的。

**Comment by networm** [comment]
所以有没有可能先临时修复一下，让这个扩展可以正常用，后续再说升级的问题？

**Comment by maicss** [comment]
也行，等明天吧

**Comment by networm** [comment]
好的，非常感谢

**Comment by maicss** [comment]
已经提交审核了，有问题再联系我。
